### ISSUE TITLE
Add glossary to docs?

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#113]
Maybe we need a glossary page with linkable quick explanations of common V8 concepts, such as "Smi".

**Comment by gengjiawen** [comment]
That will be really helpful. I am still not a clue what `Smi` is.

**Comment by gengjiawen** [comment]
Also add `torque`.

**Comment by camillobruni** [comment]
Declaring bug bankruptcy after 4 years of inactivity.
