### ISSUE TITLE
Consider hosting V8 tools under /tools

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#121]
We could host the HTML files + assets for Turbolizer, parse-processor, etc. under `v8.dev/tools/*` if we wanted to.

This seems like a good idea, but an open question remains how we'll keep it in sync with the V8 repo. Requiring a manual PRs for every change seems awkward. We could set up a bot to automate sending such PRs, but there'd still be some overhead.

Ideally, we'd be able to simply proxy through to the source files in the V8 repo. Perhaps using a rawgit-like Firebase function is the way to go here?

**Comment by SamB** [comment]
This could indeed be quite useful, at least assuming that the tools are backward-compatible.

For instance, the instructions at https://v8.dev/docs/profile might easily be usable with node *without* a v8 checkout, if only it could link to live copies of profvis/profview.

**Comment by mathiasbynens** [comment]
This is now being worked on over at https://github.com/v8/tools. Once things have settled here we can add a `/tools` page to v8.dev with links to the latest online versions.

**Comment by mathiasbynens** [comment]
https://v8.dev/tools now redirects. Closing for now.
