### ISSUE TITLE
Consider adding RSS/Atom support

### ISSUE THREAD

**Issue by aviralg** [v8/v8.dev#126]

**Comment by mathiasbynens** [comment]
It's already there. Our Atom feed is at <https://v8.dev/blog.atom>, as advertised in the HTML:

```html
<link href=/blog.atom rel=alternate title="V8 Atom feed" type=application/atom+xml>
```

**Comment by HKalbasi** [comment]
I didn't find it as a user until I came here for raising an issue. Can it be a small visible link somewhere?
