### ISSUE TITLE
Consider adding ToC for larger documentation entries

### ISSUE THREAD

**Issue by szuend** [v8/v8.dev#131]
I was just browsing the Torque user manual and thought a table of contents or something similar would be nice for larger articles. Especially for articles like the torque user manual, where readers might only be interested in one specific section.

**Comment by mathiasbynens** [comment]
I started looking into this, and then hit https://github.com/Oktavilla/markdown-it-table-of-contents/issues/38. Luckily, we can work around it, but it’s feels dirty.

WIP branch: https://github.com/v8/v8.dev/compare/toc?expand=1 (We still need to tweak the output HTML and add some styling.)

**Comment by camillobruni** [comment]
Declaring bug bankruptcy after 4 years of inactivity.
