### ISSUE TITLE
"V8 Design Elements" doc missing

### ISSUE THREAD

**Issue by curiousleo** [v8/v8.dev#133]
https://v8.dev/docs/embed#advanced-guide (source: https://github.com/v8/v8.dev/blob/master/src/docs/embed.md) contains a link to https://v8.dev/docs/design-elements with the link text "V8 Design Elements". There is no page there (it's a 404).

The [relevant wiki page](https://github.com/v8/v8/wiki/Design-Elements) says the page has moved to https://v8.dev/ but I couldn't find anything on v8.dev that looked like a "design elements" doc.

**Comment by mathiasbynens** [comment]
The Design Elements doc was heavily outdated, and has been removed. Would you be willing to submit a patch removing the link from `embed.md`?
