### ISSUE TITLE
Docs on Blink layout tests seems outdated

### ISSUE THREAD

**Issue by xtuc** [v8/v8.dev#139]
https://v8.dev/docs/blink-layout-tests

I'm having troubles with the third point (rebaselining the tests in Chromium), if you try to commit `[ NeedsRebaseline ]` it will fail during presubmit checks (as you can see [here](https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8922883557741052336/+/steps/presubmit/0/stdout)).

Another document exists with a manual way to do it (which is known to work): https://chromium.googlesource.com/chromium/src/+/master/docs/testing/web_tests.md#Rebaselining-Web-Tests.

**Status**: I'm currently following it and I can report the result here.

**Comment by MayaLekova** [comment]
Hey Sven, thanks for pointing this out! As you said, it would be really nice to post results here, to ensure that this new link describes a sound procedure. Then we'll update it in the docs.

**Comment by xtuc** [comment]
`NeedsRebaseline` or `Rebaseline` are invalid assertions, I ran into it both during the presubmit or while trying to rebaseline manually (`tools/run_web_tests.py`). I could find those indications in the Chromium documentation. The list of token is available [here](https://chromium.googlesource.com/chromium/src.git/+/master/third_party/blink/tools/blinkpy/web_tests/models/test_expectations.py#312).

**Comment by mathiasbynens** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=735176 seems relevant:

> Pretty soon, `NeedsRebaseline` will be removed (bug 692811).
> 
> Now there's `NeedsManualRebaseline` and `Rebaseline`. In practice, what these actually mean is:
>
> - `NeedsManualRebaseline` means "run the test but ignore the results"
> - `Rebaseline` means "select this test when `webkit-patch rebaseline-expectations` is run"

**Comment by xtuc** [comment]
Also an example CL would be very helpfull, just to make sure the change make sense.

**Comment by MayaLekova** [comment]
@xtuc Please check whether my last commit reflects the experience that you had. Once your CL in Chromium lands, I'd be happy to also link it in the docs as an example, that's a great idea!

Re:
> * I would expect the `tools/run_web_tests.py --reset-results` flag to update the TestExpectations file, however it doesn't.

AFAIK, the automatic updating of the TestExpectations file will work only when you make changes in Chromium itself, not in V8, because we can't synchronize rolling V8 into Chromium with this update. That's why we fall back to the manual process and you need to do the whole skip-unskip dance with the TestExpectations file.

**Comment by xtuc** [comment]
> AFAIK, the automatic updating of the TestExpectations file will work only when you make changes in Chromium itself, not in V8 [...].

Ah! that make sense.

**Comment by xtuc** [comment]
Thanks for the changes @MayaLekova, I commented on your commit.

**Comment by MayaLekova** [comment]
Thanks, @xtuc! Applied your comments to the text, sorry for the delay.

**Comment by mathiasbynens** [comment]
Closing per #146.
