### ISSUE TITLE
Update outdated docs mentioning Google Code

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#14]
https://v8.dev/docs/source-code#viewing-the-try-server

**Comment by mathiasbynens** [comment]
@natorion Could you update this please?

**Comment by mathiasbynens** [comment]
Hmm, there’s also https://v8.dev/docs/d8-android#prerequisites.

**Comment by natorion** [comment]
Sergiy, could you please update this with the latest information?

**Comment by rryk** [comment]
I am not sure how to edit that page. Is there some link I should use or could it be that I lack edit access?

**Comment by rryk** [comment]
Oh. Nvm, found "edit" link.

**Comment by rryk** [comment]
I've updated the link. Authentication is not necessary anymore, hence removed any mention of it. I wonder why would anyone want to view the tryserver though? Normally, users are interested in builder results on their CLs, which is displayed directly in Gerrit. Should I perhaps replace that section with instructions on how to view tryjob results from the command line, i.e. git-cl-try-results?

**Comment by mathiasbynens** [comment]
@rryk That sounds more useful indeed. Please submit a PR with those follow-up changes!

**Comment by rryk** [comment]
I've updated https://github.com/v8/v8.dev/blob/master/src/docs/source-code.md. How do I submit a PR?

**Comment by mathiasbynens** [comment]
You're one of the few people with admin access to this repo, so you can push to the master branch directly. However, it's generally preferred to create a new pull request for any changes. That way we can review the changes and run CI checks before landing it. :) Thanks!

**Comment by rryk** [comment]
Thanks for explaining. I'll use a PR request next time.
