### ISSUE TITLE
Update outdated docs mentioning GYP

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#16]
https://v8.dev/docs/d8-android

**Comment by mathiasbynens** [comment]
@hashseed Do you know what the GYP-less workflow is like? If so, could you update the docs please?

**Comment by hashseed** [comment]
@ulan

**Comment by ulan** [comment]
We have https://v8.dev/docs/cross-compile-arm that describes how to build d8 using GN.

So I think https://v8.dev/docs/d8-android can be removed.
