### ISSUE TITLE
Import remaining WebFu content

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#192]
- [ ] https://developers.google.com/web/updates/2017/07/upcoming-regexp-features by @schuay and @hashseed
- [ ] https://developers.google.com/web/fundamentals/primers/async-functions by @jakearchibald
- [ ] https://developers.google.com/web/fundamentals/primers/promises by @jakearchibald

**Comment by camillobruni** [comment]
Declaring bug bankruptcy after 4 years of inactivity.
