### ISSUE TITLE
question: why doesn't Javascript have optional static typing ? 

### ISSUE THREAD

**Issue by catastrop** [v8/v8.dev#199]
tc39 is adding new things to JS. But why not optional static typing ?

If they do it, we don't have to use Typescript anymore and being able to pass type information to the engine.

We will have less dev dependency.

**Comment by jakobkummerow** [comment]
This is the wrong bug tracker to discuss what TC39 does or doesn't do. Consider asking on the es-discuss mailing list. 

That said, from an engine's point of view, the short answer is: the "types" in TypeScript are useful for developer productivity, but not useful for engine performance, so we have no particular incentive to drive such an initiative.
