### ISSUE TITLE
Some doc links => 404

### ISSUE THREAD

**Issue by alrra** [v8/v8.dev#20]
e.g.:

https://v8.dev/docs/turbofan
https://v8.dev/docs/ignition
https://v8.dev/docs/untrusted-code-mitigations
...

**Comment by mathiasbynens** [comment]
Fixed by fdffe71897d35d07821c9bb0986359d7ed8ca4da. (I had already corrected the casing of the files on my local system, but because I’m using macOS which is case-insensitive, it didn’t get picked up. Bleh!)
