### ISSUE TITLE
Translation v8.dev into different languages

### ISSUE THREAD

**Issue by myshov** [v8/v8.dev#203]
Hello!

First of all, thank you for your work on this precious resource.

I have a proposal. It would be cool to see translation of articles in the blog into different languages. What do you think?

I think the community will help with translation (for example I can help with translation to Russian). In the code itself we need to add some changes to static site generator and add button for changing of language of the article.

**Comment by justjavac** [comment]
I can help with translation to Chinese

**Comment by mathiasbynens** [comment]
Thanks for the suggestion, and thank you for offering to help with translations! <3

Some concerns that we'd need to address before we do this:

The main concern I have is about the translations becoming out of date with the English version. How do we deal with updating content?

**Comment by myshov** [comment]
The first thing that comes to mind is a new issue in repo. Already translated articles, that needs to be updated, could be marked as outdated before updating of translation, it will help readers to see actual status of translation.

**Comment by camillobruni** [comment]
Declaring bug bankruptcy after 4 years of inactivity.
