### ISSUE TITLE
Automate feature support data updates

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#212]
For [the feature support listings](https://v8.dev/features/support) on [v8.dev/features](https://v8.dev/features), we started small and shipped a manually maintained version. The maintenance overhead is acceptable, since once a feature ships in any one environment, we can update our feature support listing, and then we (generally) never have to update that specific feature+environment entry again.

However, it would be nice to automate this whole thing, and use a centralized data source like ChromeStatus, CanIUse, or MDN.

**Comment by mathiasbynens** [comment]
cc @RReverser

**Comment by mathiasbynens** [comment]
Per https://twitter.com/floscholz/status/1171147561098518530, MDN might offer embeds soon. Still, we'd likely want to use the data directly at build time, and turn it into HTML, reducing the need for third-party HTTP requests.

**Comment by camillobruni** [comment]
Declaring bug-bankruptcy after >4 years of inactivity.
