### ISSUE TITLE
Add automated checks for src/_img/avatars/*

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#224]
All images in `src/_img/avatars/*` follow certain conventions:

- JPEG format
- the `@2x` version is named `first-last@2x.jpg` and must be exactly 192×192px
- the `@1x` version is named `first-last.jpg` and must be exactly 96×96px
- all images must be optimized i.e. below a certain file size threshold (10 kB?)
    - I tend to use [Squoosh](https://squoosh.app) with MozJPEG @ quality=75, and then run the result through `ImageOptim.app` with “optimization level” set to “insane” for further savings.

All of the above could use automated CI checks, so that we don’t accidentally merge PRs that deviate from the convention.

**Comment by camillobruni** [comment]
PR #745 will make this obsolete by reducing complexity.
