### ISSUE TITLE
V8 API documentation

### ISSUE THREAD

**Issue by devsnek** [v8/v8.dev#234]
For a long time, https://v8.paulfryzel.com/docs/master was the place to go for up-to-date documentation on V8's public (and private) API surface. Unfortunately, this incredible resource is no longer maintained. v8.dev seems like an excellent place to host an official version of doxygen, although I don't know exactly how one would go about wiring that up. Perhaps a github action on https://github.com/v8/v8?

**Comment by mathiasbynens** [comment]
PTAL @ulan @natorion

**Comment by ulan** [comment]
I am not the right owner for this. Add people who might be interested @hashseed @mi-ac

**Comment by natorion** [comment]
This sounds reasonable, if we can fully automate it with low effort. @tmrts any clue how involved this might be?

@hannespayer might be interested in this too.

**Comment by mathiasbynens** [comment]
ping @tmrts

**Comment by LeszekSwirski** [comment]
I've created https://v8.github.io/api/head/ for this, manually updated for now but we can automate it at some point.
