### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by jonathanmarvens** [v8/v8.dev#240]
Unfortunately, [v8.dev](https://v8.dev) has been down for _at least_ a week now. Are y’all aware of this?

Thank you.

**Comment by dtig** [comment]
Just checked now, looks like it's working for me.

**Comment by jonathanmarvens** [comment]
@dtig Thank you. I’m guessing that the server might be dropping my requests since I use a *VPN*? All of this time, I just assumed it was down for everyone 😕

**Comment by dtig** [comment]
No problem, closing this issue as the website seems to be up and running. Hope you are able to figure out why your requests are getting dropped!

**Comment by jonathanmarvens** [comment]
@dtig This is an issue with the website’s configuration though; my network is fine. When I try [v8.dev](https://v8.dev) from my tablet without VPN, it works, but on my laptop with VPN, all of my requests are dropped. Barring disabling my VPN (which is a non-option for me on my laptop, unfortunately), there’s nothing that I can do on my end. Is there a policy against VPN users? If not, can y’all update the firewall settings?
