### ISSUE TITLE
Add Torque documentation

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#25]
`/docs/torque` would be nice.

https://v8.dev/docs/csa-builtins could be updated to cross-reference it, or even be replaced by it.

This is important since we currently recommend that all new built-ins are written in Torque.

cc @dannoc

- https://docs.google.com/document/d/1GU1ubYuNY5GSQvS874hB4xP2wopleo-X-DR4DUwFWAE/edit
- [Torque user manual](https://docs.google.com/document/d/1oC_XLE71wxAlCabuyf8j_Wplq7yfiZshS3xWsU51AzU/edit)

**Comment by mathiasbynens** [comment]
Leaving this issue open until https://v8.dev/docs/csa-builtins is updated to point to https://v8.dev/docs/torque, and possibly marked as deprecated (?). cc @tebbi

**Comment by thysultan** [comment]
On the topic of syntax highlighting: Is the TypeScript syntax package(sublime) close enough?

**Comment by mathiasbynens** [comment]
It’s better than nothing, but Torque is different enough that it’s worth having a separate highlighter for.

**Comment by mathiasbynens** [comment]
@tebbi @danno Should https://v8.dev/docs/csa-builtins be updated to point to https://v8.dev/docs/torque, and possibly even be marked as deprecated? Can someone submit a patch please?

**Comment by dannoc** [comment]
I am not sure we're ready to deprecate the CSA docs fully, but we certainly
should provide an equivalent Torque intro and how-to. Tobias, is this
something you might be willing to update?


Daniel Clifford |  Tech Lead & Manager, V8 |  Google Germany GmbH |  Erika-Mann
Str. 33, 80636 München

Registergericht und -nummer: Hamburg, HRB 86891 | Sitz der Gesellschaft:
Hamburg | Geschäftsführer: Paul Manicle, Halimah DeLaine Prado

**Comment by tebbi** [comment]
I agree, it makes sense to port this guide to Torque. I'll do that.

**Comment by dannoc** [comment]
Cool, thanks!

**Comment by mathiasbynens** [comment]
Closing since https://v8.dev/docs/torque now exists.
