### ISSUE TITLE
Table colors need some tuning in dark mode

### ISSUE THREAD

**Issue by chicoxyzzy** [v8/v8.dev#258]
![image](https://user-images.githubusercontent.com/1507086/66344518-cac6db80-e956-11e9-94c2-9964ebf62027.png)

https://v8.dev/features/promise-combinators

**Comment by mathiasbynens** [comment]
https://github.com/v8/v8.dev/blob/f49faf6b6fe03fa8c14c6211afeaf6605f4686e4/src/_css/main.css#L380-L382

**Comment by mathiasbynens** [comment]
#### Light

![](https://user-images.githubusercontent.com/81942/66517400-ff63a000-eada-11e9-9d0a-f63e5ad2ac2e.png)

#### Dark

![](https://user-images.githubusercontent.com/81942/66517415-068aae00-eadb-11e9-92a0-b1afef2c66b9.png)

**Comment by GottZ** [comment]
for some reason i think this should also happen:

`--table-border: var(--darkgray);`

**Comment by mathiasbynens** [comment]
I actually tried it but I thought it looked worse in combination with the blue.
