### ISSUE TITLE
Some titles display HTML escape codes in the title bar

### ISSUE THREAD

**Issue by psmarshall** [v8/v8.dev#26]
e.g. In the title for this page, `&amp;` shows in the title bar.

![v8_dev_bug](https://user-images.githubusercontent.com/7401419/46944075-6f2e7e80-d071-11e8-9e00-618086a7c621.png)

**Comment by mathiasbynens** [comment]
The current fix assumes the actual plain-text title won't ever contain HTML character references, which seems like a reasonable assumption for this website.
