### ISSUE TITLE
Re-render twitter widget on color scheme change

### ISSUE THREAD

**Issue by RReverser** [v8/v8.dev#260]
Currently, when changing color scheme via either system settings or the toggle, Twitter widget remains in its initial scheme and looks out of place.

**Comment by tomayac** [comment]
FYI, the `<dark-mode-toggle>` emits a [`colorschemechange`](https://github.com/GoogleChromeLabs/dark-mode-toggle#events) event that you can listen for and then re-trigger the Twitter widget insertion.

**Comment by RReverser** [comment]
Yeah, it's the widget insertion that is tricky. Twitter replaces the original element, so one would need to either re-insert it from JS or rewrite widget integration to use their JS API.

**Comment by tomayac** [comment]
I think for the moment removing and reinserting is the only way this works :-/

**Comment by RReverser** [comment]
@tomayac Do you want to give it a shot?

**Comment by tomayac** [comment]
Happy to, feel free to assign me.
