### ISSUE TITLE
Add Lighthouse size budget

### ISSUE THREAD

**Issue by tomayac** [v8/v8.dev#269]
We want to control the size of our JavaScript, this is a meta issue to remind us to [set up Lighthouse](https://developers.google.com/web/tools/lighthouse/audits/budgets#setup) to track this for us, ideally [automatically via Travis](https://github.com/GoogleChromeLabs/lighthousebot).

**Comment by camillobruni** [comment]
Declaring bug bankruptcy after 4 years of inactivity.
