### ISSUE TITLE
Serving locally requires login

### ISSUE THREAD

**Issue by natorion** [v8/v8.dev#27]
```
hablich@host~/src/v8.dev$ npm start

> @ start .../hablich/src/v8.dev
> firebase serve --port=9001


Error: Command requires authentication, please run firebase login
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `firebase serve --port=9001`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .../hablich/.npm/_logs/2018-10-15T14_25_38_340Z-debug.log
```

**Comment by mathiasbynens** [comment]
Per https://github.com/firebase/firebase-tools/issues/302, this is by design :( Looks like we'll have to use superstatic directly instead of `firebase serve`.

**Comment by socsieng** [comment]
For anyone looking for a solution to this: https://github.com/firebase/firebase-tools/issues/302#issuecomment-797122096

> For me, I needed firebase functions support and found that `firebase emulators:start` didn't require login.
> 
> Instead of `firebase serve --port 8080`, I now use `firebase emulators:start` with an updated `firebase.json` file:
> 
> ```js
> {
>   "functions": { /* ... */ },
>   "hosting": { /* ... */ },
>   "emulators": {
>     "hosting": {
>       "port": "8080"
>     },
>     "functions": {
>       "port": "8081"
>     },
>     "ui": {
>       "enabled": false
>     }
>   }
> }
> ```
