### ISSUE TITLE
Low or no contrast text colours

### ISSUE THREAD

**Issue by declanbyrd** [v8/v8.dev#274]
While in dark mode, on the dynamic import documentation page some of the links are either difficult to read because the contrast is low, or in this case there are words with no contrast to the background.

![image](https://user-images.githubusercontent.com/24387679/67635346-d0f90980-f8bd-11e9-9318-f5ec4f3b5d0a.png)

Light theme for comparison:
![image](https://user-images.githubusercontent.com/24387679/67635403-99d72800-f8be-11e9-9f66-1643d6502998.png)

In main.css the colour of the links and note background are the same for dark mode:

```CSS
:root.dark {
  --main-and-footer-link-color: var(--yellow);
  --note-background: var(--yellow);
}
```

I'd be happy to create a PR to fix this with a bit of guidance to align with the style guide.

**Comment by mathiasbynens** [comment]
Thanks for spotting and reporting this, @declanbyrd! A PR would be amazing.

Re: guidance, the general rule is to follow the style of the surrounding code (which in the case of CSS isn’t that much). Please let us know if there’s any specific questions you have. cc @tomayac @RReverser
