### ISSUE TITLE
Why I can't add PWA to my phone in Safari 13

### ISSUE THREAD

**Issue by thoamsy** [v8/v8.dev#275]
I can add the V8 to my home page in the Mac, but I can't get a PWA page in my iPhone.

You can see the screenshot in the below, the icon is not **the v8 logo**:
![IMG_1520](https://user-images.githubusercontent.com/11444431/67824769-45bc8580-fb02-11e9-8541-aaaf332f7940.png)

I am not sure if it is caused by compatibility issues.

**Comment by tomayac** [comment]
My suggestion would be to conditionally (based on UA sniffing) load @samthor's [PWACompat](https://github.com/GoogleChromeLabs/pwacompat).

```js
if (/\b(iPad|iPhone|iPod)\b/.test(navigator.userAgent)) { import('https://unpkg.com/pwacompat'); }
```

The above line works like a charm:

![image](https://user-images.githubusercontent.com/145676/68302147-b8e56f00-00a1-11ea-8b47-100b155f87a2.png)
