### ISSUE TITLE
CSS: Switch border-bottom for proper text-decoration (and text-decoration-skip-ink)

### ISSUE THREAD

**Issue by tomayac** [v8/v8.dev#279]
Discussed in the context of https://github.com/v8/v8.dev/pull/278#discussion_r343086049.

**Comment by mathiasbynens** [comment]
To clarify [my earlier comments](https://github.com/v8/v8.dev/pull/278#discussion_r343084953), there’s no technical reason I used `border` over anything else, but I do like the way the current styles look (as in, the “underline” is a few pixels away from the text). Can we achieve that with `text-decoration`?

I’m open to the change either way, just wondering how much of a visual impact it would have.

**Comment by tomayac** [comment]
There's [`text-underline-offset`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-offset), but browser support isn't great at the moment. I don't see this as a blocker, though.

**Comment by camillobruni** [comment]
Declaring bug bankruptcy after 4 years of inactivity.
