### ISSUE TITLE
Fix styling for wide headings on narrow viewports

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#281]
e.g. https://v8.dev/features/string-replaceall or https://v8.dev/features/symbol-description

![](https://user-images.githubusercontent.com/81942/68602299-f3148f00-045a-11ea-938e-8ffc7861f765.png)

(Reported via Twitter: https://twitter.com/saschaplas/status/1193918922682032128)

**Comment by RReverser** [comment]
Reopening to track issue on iOS Safari: https://twitter.com/tomayac/status/1234565673277370368
