### ISSUE TITLE
Set up Lighthouse CI

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#283]
https://github.com/GoogleChrome/lighthouse-ci

**Comment by mathiasbynens** [comment]
Ran into a few issues along the way:

- https://github.com/GoogleChrome/lighthouse-ci/issues/62
- https://github.com/GoogleChrome/lighthouse-ci/issues/63

**Comment by camillobruni** [comment]
Declaring bug bankruptcy after 4 years of inactivity.
