### ISSUE TITLE
Set up travis-size-report / compressed-size-action

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#285]
https://github.com/GoogleChromeLabs/travis-size-report

**Comment by mathiasbynens** [comment]
@developit built a thing that's like `travis-size-report` with a GitHub auto-commenting bot, and we should use it here!

**Comment by mathiasbynens** [comment]
https://github.com/marketplace/actions/compressed-size-action

**Comment by camillobruni** [comment]
Declaring bug bankruptcy after 4 years of inactivity.
