### ISSUE TITLE
Styling issue with code blocks within a note

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#304]
![image](https://user-images.githubusercontent.com/81942/71015493-f9e68f80-20f3-11ea-95f3-2cd7a7377df0.png)

cc @tomayac since this reminds me of the similar issues he fixed with nested code blocks

**Comment by tomayac** [comment]
Can repro, but on mobile at the moment. Pleased to assign me, I am happy to have a look tomorrow.
