### ISSUE TITLE
Service worker fails to register if using uBlock origin

### ISSUE THREAD

**Issue by domenic** [v8/v8.dev#32]
```
workbox-sw.js:1 Unable to import module 'workbox-google-analytics' from 'https://storage.googleapis.com/workbox-cdn/releases/3.6.1/workbox-google-analytics.prod.js'.
loadModule @ workbox-sw.js:1
get @ workbox-sw.js:1
(anonymous) @ sw.js:1
workbox-sw.js:1

Uncaught 
loadModule @ workbox-sw.js:1
get @ workbox-sw.js:1
(anonymous) @ sw.js:1

(index):1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed
```

Might be more of a workbox issue, but seems bad.

**Comment by mathiasbynens** [comment]
cc @jeffposnick

**Comment by mathiasbynens** [comment]
This seems to be https://github.com/GoogleChrome/workbox/issues/1186 + https://github.com/GoogleChrome/workbox/issues/1646. I’ll leave this issue open as a reminder to update our Workbox version once this is fixed upstream.

**Comment by jeffposnick** [comment]
Yup. You can move to `4.0.0-alpha.0` if you want to do something now, and pick up the renamed scripts.
