### ISSUE TITLE
Revisit `extras` folder

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#339]
https://v8.dev/blog/understanding-ecmascript-part-2 points to some extra content, currently at https://v8.dev/blog/extras/understanding-ecmascript-part-2-extra.

This breaks our URL design. The above implies the existence of `https://v8.dev/blog/extras` but that 404s, and it doesn’t really make sense to create it.

We should move the extra content to a separate section in the main blog post, and [set up a redirect](https://github.com/v8/v8.dev/blob/709ddfdca87965cdcd7684526531dcda55a461b5/firebase.json#L5). If the goal is to hide the extra content by default, we can use `<details>`.

**Comment by camillobruni** [comment]
Declaring bug bankruptcy after 4 years of inactivity.
