### ISSUE TITLE
Duplicate text in Pointer Compression post?

### ISSUE THREAD

**Issue by kripken** [v8/v8.dev#350]
Just above [this link](https://v8.dev/blog/pointer-compression#compressed-tagged-values-and-new-heap-layout) this text appears. Maybe only one of the two paragraphs is needed?

> You may notice that unlike 32-bit architectures, on 64-bit architectures V8 can use 32 bits for the Smi value payload. The benefits of 32-bit Smis will be discussed in the following sections.
>
> You may notice that unlike 32-bit architectures, on 64-bit architectures V8 can use 32 bits for the Smi value payload. The implications of 32-bit Smis on pointer compression will be discussed in the following sections.

cc @santiaboy @RReverser

**Comment by santiaboy** [comment]
Nice catch. Fixing it now.

**Comment by RReverser** [comment]
Fixed on master.
