### ISSUE TITLE
Explicit image dimensions are ignored and result in significant layout jumps

### ISSUE THREAD

**Issue by RReverser** [v8/v8.dev#370]
Currently, we set (or, now, generate) explicit `width` and `height` on all images, presumably to avoid layout jumps.

However, these dimensions are getting completely ignored and overridden by https://github.com/v8/v8.dev/blob/cf7598164fdc7a881f93f4a6f058ac95bb5a110e/src/_css/main.css#L412-L416 and result in different sizes once image is loaded.

This results in a significant amount of layout jumps while scrolling through the document, especially due to combination with our extensive usage of `loading="lazy"`.

In order to verify, go to an image-heavy post, e.g. https://v8.dev/blog/pointer-compression/, open DevTools and paste:

```js
[document.body.clientHeight, ...$$('img').map(img => `${img.offsetWidth}x${img.offsetHeight}`)]
```

On my computer, it results in:

```json
[22875, "600x371", "764x240", "764x336", "764x764", "764x764", "764x764", "764x764", "764x764", "764x764", "764x764", "764x764", "600x600", "600x600", "96x96", "96x96"]
```

You can see how any images outside the immediate viewport resulted in 1:1 dimensions (squares) with explicit `height` completely ignored.

Then, scroll through the document to the end and try same expression again:

```json
[18141, "600x371", "764x240", "764x336", "764x336", "764x183", "764x158", "764x336", "764x267", "764x213", "764x103", "764x241", "600x371", "600x371", "96x96", "96x96"]
```

Now that images are loaded, all the heights got updated to actual dimensions from the image itself and the total document height shrunk by 4,734 pixels.

cc @mathiasbynens and @tomayac as it looks like you gave this some thought as part of removal of `intrinsicsize` in #231 / #232 and might have ideas on how to fix this.

**Comment by RReverser** [comment]
Looks like simply removing `height: auto` fixes the problem, but not 100% sure if there are any unwanted side-effects from doing that?

**Comment by tomayac** [comment]
Please don’t remove [this](https://github.com/v8/v8.dev/blob/cf7598164fdc7a881f93f4a6f058ac95bb5a110e/src/_css/main.css#L412-L416). See https://youtu.be/4-d_SoCHeWE for why it’s there. All browsers have agreed to put the aspect ratio in the UA stylesheet. It’s gonna be good.

**Comment by tomayac** [comment]
It seems to be working perfectly fine today. There's no content jump at all:

<img width="488" alt="Screen Shot 2020-04-06 at 11 00 36" src="https://user-images.githubusercontent.com/145676/78541437-ea4f9b80-77f5-11ea-8e0e-6d53353ea355.png">

<img width="468" alt="Screen Shot 2020-04-06 at 11 00 42" src="https://user-images.githubusercontent.com/145676/78541460-eface600-77f5-11ea-92fe-215b49c62db6.png">

It's calculating the aspect ratio based on `width` and `height`, leaves exactly the space it needs given the current actual width, and that's it. This is also [what we recommend officially](https://web.dev/native-lazy-loading/#image-loading).

**Comment by mathiasbynens** [comment]
@RReverser Not sure if this context was clear, so I'll say it just in case: the `height: auto` is needed for the case where an image gets downsized on a narrow viewport.

**Comment by RReverser** [comment]
@mathiasbynens That seems to be doing the opposite, as far as I can tell - if you look at e.g. the 4th image, its specified dimensions are `<img width="827" height="363" ... />`.

With `height: auto` it's currently downsized to `764x764` before image is loaded, and to `764x336` when it's loaded; however, when I comment out `height: auto`, then it's getting downsized with correct aspect-ratio to `764x336` even before the image is loaded, which seems like the desired behaviour?

**Comment by RReverser** [comment]
@tomayac You're looking at the first image, which, as you can see from the calculated image in issue description, is correct right away anyway. This is because that image is getting preloaded right away, because it's in the viewport, so it's much harder to catch the point where it has incorrect dimensions.

It's images outside the initial viewport (which, correspondingly, aren't visible on screenshot) that are the issue and cause document height to jump - this is visual noticeable only via the length of scrollbar, but still causes layout jumps as you scroll, as can be seen from calculated dimensions.

**Comment by RReverser** [comment]
> It's calculating the aspect ratio based on width and height, leaves exactly the space it needs given the current actual width, and that's it.

It's really not, and that's the point of the issue report :( If we recommend if officially, then it's either a bug in Chrome that needs to be fixed, or we need to change our recommendation.

**Comment by RReverser** [comment]
> however, when I comment out height: auto, then it's getting downsized with correct aspect-ratio to 764x336 even before the image is loaded, which seems like the desired behaviour?

Nvm, removing `height: auto` causes issue *after* image is loaded instead.

Would still appreciate suggestions for a proper fix from someone who knows more.

**Comment by camillobruni** [comment]
Declaring bug bankruptcy after 4 years of inactivity.
