### ISSUE TITLE
Run  build script   generates an error  

### ISSUE THREAD

**Issue by erossszh** [v8/v8.dev#43]
![image](https://user-images.githubusercontent.com/40795291/47404020-52cfc780-d77e-11e8-966a-f9146f8e2035.png)

on the other hand,when i  run start   and   then   input  'http://localhost:9001'  in chrome,the response is

![image](https://user-images.githubusercontent.com/40795291/47404366-a1319600-d77f-11e8-9215-b7e63e232ca0.png)

thanks:)

**Comment by mathiasbynens** [comment]
It looks like you didn't follow the steps in <https://github.com/v8/v8.dev#local-setup>.

- Use the expected Node.js version
- Don't run `eleventy` directly; instead, use the `npm run` scripts

**Comment by erossszh** [comment]
@mathiasbynens thank you!  My node version  is  v8.9.3, this is the wrong place :)
