### ISSUE TITLE
A syntax error in "V8 release v8.4"

### ISSUE THREAD

**Issue by CyberSaxosTiGER** [v8/v8.dev#435]
I think there is a syntax error in "V8 release v8.4" line 96

```javascript
class Component {
  #privateMethod() {
    console.log('I'm only callable inside Component!');
  }
  get #privateAccessor() { return 42; }
  set #privateAccessor(x) { }
}
```
I think we should change single quote with double quote
```diff
<     console.log('I'm only callable inside Component!');
---
>     console.log("I'm only callable inside Component!");

```

**Comment by LeszekSwirski** [comment]
This is actually Google JavaScript code style: https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes

**Comment by CyberSaxosTiGER** [comment]
I does not meant that.
the single quote of `I'm` is colliding with console.log's single quote

**Comment by LeszekSwirski** [comment]
Ah whoops, my mistake, good catch in that case!
