### ISSUE TITLE
Auto-add table-wrapper via custom Markdown rendering

### ISSUE THREAD

**Issue by RReverser** [v8/v8.dev#456]
I've seen @mathiasbynens's suggestion that table-wrapper should be added to all (?) tables. If that's correct, we probably want to automate this via custom Markdown plugin, similarly to custom image render.

**Comment by mathiasbynens** [comment]
Just to confirm: yes, it must be added to all tables. The wrapper is needed for narrow viewports. Thanks for taking a look!

**Comment by camillobruni** [comment]
Declaring bug bankruptcy after 4 years of inactivity.
