### ISSUE TITLE
Support alternate image formats (e.g. AVIF)

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#460]
Now that Chrome ([and Squoosh!](https://github.com/GoogleChromeLabs/squoosh/pull/804)) support AVIF, it would be nice to be able to provide images in multiple formats and have that result in `<picture>` + `<source>` + `<img>`. Perhaps this can be done without any Markdown-level changes. For example, this existing syntax:

```markdown
![](/_img/v8-lite/v8-lite.avif)
```

…could at build time check if `v8-lite.png` or `v8-lite.jpg` exist at the same location, and if so, output `<picture>` + `<source>` + `<img>`.

**Comment by mathiasbynens** [comment]
(Note that we could also check for `.webp` but given that AVIF is better I don't think we'd want to bother.)

cc @RReverser since you recently awesome-ified `![]()`, and this seems like a next step.

**Comment by jridgewell** [comment]
Shouldn't this be done at the server level, so we don't need to upload an ever increasing number of image formats? Just upload a single image of the highest quality, and let the content negotiation headers handle which image format to serve.

**Comment by mathiasbynens** [comment]
Related: https://github.com/v8/v8.dev/pull/462 tackles this for the avatars (which are hardcoded in the HTML templates).

> Shouldn't this be done at the server level, so we don't need to upload an ever increasing number of image formats? Just upload a single image of the highest quality, and let the content negotiation headers handle which image format to serve.

We currently use static Firebase hosting. For content negotiation, I imagine we’d need to start adding cloud functions — is that right? It’s certainly possible, but IMHO it seems simpler to start with manually supplying the images in all desired formats.

**Comment by RReverser** [comment]
> We currently use static Firebase hosting. For content negotiation, I imagine we’d need to start adding cloud functions — is that right?

I'm once again tempted to suggest adding Cloudflare in front of v8.dev. Among other things, they have automatic WebP optimisation, and are working on AVIF too AFAIK.

**Comment by camillobruni** [comment]
I don't think this is relevant for the amount of traffic that is generated by v8.dev (plus we want to keep this as low maintenance as possible, the fewer automation and indirections needed the better).
Slowly manually migrating everything to AVIF is an easy fix in the long run.
