### ISSUE TITLE
Webpage on v8.dev blog not rendering HTML

### ISSUE THREAD

**Issue by indiescripter** [v8/v8.dev#464]
At this blog URL https://v8.dev/blog/web-tooling-benchmark ,

> Announcing the Web Tooling Benchmark
Published 06 November 2017 · Tagged with benchmarks Node.js

Clicking on *Node.js* item to the right of *benchmarks* takes the browser to URL

https://v8.dev/blog/tags/node.js

which is HTML text but is being send to the browser by the origin server with `text/javascript` content-type.

Looks like the backend is being tricked into sending `text/javascript` rather than `text/html` simply because the URL ends in `.js`

Suggest workaround is to drop the `.js` suffix & change that blog tag to simply "Node" as per adoption in this book:

https://subscription.packtpub.com/book/web_development/9781849515146/1/ch01lvl1sec10/spelling-node-node-js-or-node-js

**Comment by MyIsaak** [comment]
Hi @indiescripter, I reproduced your issue and provided a PR. Please check it out, thanks!

**Comment by indiescripter** [comment]
Hey @MyIsaak, thank you plus looks like you went to all the trouble to sign the Google CLA.

I'm cloning your patch branch right now; will build, test & let you know. Is it possible/useful to add my handle to the Assignees field in your PR (or maybe that's only for v8.dev admin to do on their side; I don't know).

Back in a while after some morning coffees. It's 5.30 am in my neck of the woods!

**Comment by indiescripter** [comment]
Hi @MyIsaak, please see my thorough test report in PR #465 comments:

https://github.com/v8/v8.dev/pull/465#issuecomment-686776204
