### ISSUE TITLE
Respectful Language Concern

### ISSUE THREAD

**Issue by PlzDontBlackListMe** [v8/v8.dev#476]
Did my username immediately set off alarm bells? 

Did the fact the "B" and the "L" are both capitalized suggest this may be more "racist" than you initially thought (It was done for ease of reading and camelCase habit). Then you my friend, are guilty of looking beyond the mark.

This account was created out of a legitimate concern my primary account would be ~~blacklisted~~ sorry, blocklisted (which just sounds like someone from the UK saying the same word).

**Issue:** https://v8.dev/docs/respectful-code

**Concern:**

I get this _comes_ from a well meaning place. People seeing the recent injustices and atrocities against African Americans looked around their sphere of influence and said something along the lines, "This is terrible what can I do?" The current line of thinking however, i.e. censoring benign words with no racial divisiveness, is looking beyond the mark and ineffective at providing any real help or change. **All it will do is vilify otherwise benign, good or even great people and projects.**

When FAANG starts doing XYZ as a "best practice" it _generally_ will pick up steam. Not all the time, but often. This has a very high likelihood of becoming the status quo. If I'm not racist but don't subscribe to this virtue signaling censorhip and I don't "get in line" then the defacto assumption will be I'm racist and my Open Source project has a very high chance of getting ~~blacklisted~~ (oops, sorry) denylisted.

[Blacklist was used as early as 1624](https://www.reddit.com/r/AskHistorians/comments/866ynp/what_are_the_origins_of_the_words_blacklist_and/dw3svkw?utm_source=share&utm_medium=web2x&context=3). It became popular during WWI and was made so by the British.

Ironically by censoring the word `master`  from git branches (Master's Degree, Master Jedi, Master Bruce Wayne, [Master William](https://www.youtube.com/watch?v=xaKsC2AwFt0) - Fresh Prince of Bel Air) any use of the the word **becomes** a racially divisive thing whereas before it wasn't.

All this will do is salve our conscience that we "did our part" when in fact we did nothing at all but unnecessarily censor a bunch of otherwise benign words. **By making them forbidden we give them racially divisive meaning** this in turn increases the means and words whereby racists can racistly express themselves.

**Comment by surma** [comment]
We are fully committed to implement the “Respectful Code” guidelines as outlined.

[The `master` branch in git comes from the master/slave dichotomy](https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html), and as such carries racist heritage that we have no interest in perpetuating. Same goes for [Blacklist/Whitelist](https://jmla.pitt.edu/ojs/jmla/article/view/490/744).
