### ISSUE TITLE
Doxygen API reference page is empty

### ISSUE THREAD

**Issue by ajklein** [v8/v8.dev#505]
On https://v8.dev/docs/api, there's a link to doxygen-generated pages for the V8 C++ API. But that page, https://v8.github.io/api/head/, is blank.

**Comment by lucasreta** [comment]
Seems fixed already, I'm greeted by a page that provides a generic introductory message explaining that it was automatically generated by Doxygen.

**Comment by ajklein** [comment]
So it seems, this now works for me.
