### ISSUE TITLE
LLDB based JIT debugging - beyond Linux

### ISSUE THREAD

**Issue by adv-sw** [v8/v8.dev#595]
https://v8.dev/docs/gdb-jit

Says Linux only bcoz ELF. Windows lldb can also JIT load ELF, but requires following patch to enable GDB/JIT functionality.

LLDB/Windows JIT patch fix here : https://reviews.llvm.org/D110066

With that integrated, can v8 JIT debug via lldb on Windows ?

**Comment by camillobruni** [comment]
gdb-jit is only partially maintained and poorly supported even on x64.
Feel free to file a bug against V8 instead of the blog post on <https://v8.dev/bug>.
