### ISSUE TITLE
Embedded V8 Crashes in snapshot serialization under LINUX 64-bit

### ISSUE THREAD

**Issue by Gumbit** [v8/v8.dev#610]
Version 9.4.146

Linux 4.18.0-305.10.2.el8_4.x86_64 #1 SMP Mon Jul 12 04:43:18 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

This fails consistently while embedded in our C++ application. We have created a standalone C++ program to demonstrate the issue. It does not fail unless it is run with Valgrind where it will fail consistently. Am attaching the Valgrind output, the sample program, compile options and the snapshot binary file.
[LinuxV8Crash.zip](https://github.com/v8/v8.dev/files/7584674/LinuxV8Crash.zip)

**Comment by Gumbit** [comment]
I am wondering whether the crash is caused during the creation of the snapshot. The snapshot creation uses a number of function template. I saw an old post (7 years old) that indicated that function templates and array objects were not supported in snapshots. If this is true, I wonder whether this may be our problem.  When the program creates the snapshot and then immediately reads it back in, it will frequently crash in the identical function that crashes under Linux. Looks like it is trying to access something called a "backing store'.

**Comment by LeszekSwirski** [comment]
This is the repository for the V8 website, please file a bug on crbug.com/v8
