### ISSUE TITLE
How to debug V8 in Xcode?

### ISSUE THREAD

**Issue by zhaosonggo** [v8/v8.dev#619]
1. gn gen  out/xcode --ide="xcode"
2. open all.xcodeproj
3. build v8_hello_world
4. add breakpoints in "sample/hello-world.cc"

but breakpoint failure，please help me

**Comment by wangym1551** [comment]
i have this problem too

**Comment by peiweippww** [comment]
I have the same problem

**Comment by a8397550** [comment]
i have this problem too

**Comment by zhaosonggo** [comment]
I have already solved this problem, and the solution is to use VSCode。^_^

**Comment by camillobruni** [comment]
This not the right issue tracker, please use https://v8.dev/bug to file new bugs.
