### ISSUE TITLE
how to debug using  %SystemBreak(); in chromium on Android platform

### ISSUE THREAD

**Issue by e10514001** [v8/v8.dev#620]
i want to debug chromium render process, so i using this:
chrome_public_apk launch --args='--js-flags="--allow-natives-syntax" --process-per-tab --wait-for-debugger-children=renderer ' 127.0.0.1:8000/my.html

and get the pid:
org.chromium.chrome 9623
org.chromium.chrome:privileged_process0 9691
org.chromium.chrome:sandboxed_process0 9656

next i attach to android process:
chrome_public_apk  gdb --pid 9656

but i all ways get "received signal SIGTRAP, Trace/breakpoint trap", where i using only  one "%SystemBreak()" in my js code:
Thread 12 "CrRendererMain" received signal SIGTRAP, Trace/breakpoint trap.
0x0000007e07839680 in ?? ()
(gdb) c
Continuing.

Thread 12 "CrRendererMain" received signal SIGTRAP, Trace/breakpoint trap.
0x0000007e07839680 in ?? ()
(gdb) c
Continuing.

Thread 12 "CrRendererMain" received signal SIGTRAP, Trace/breakpoint trap.
0x0000007e07839680 in ?? ()
(gdb) c
Continuing.

Thread 12 "CrRendererMain" received signal SIGTRAP, Trace/breakpoint trap.
0x0000007e07839680 in ?? ()
(gdb) 

help, please

**Comment by camillobruni** [comment]
Note %SystemBreak is for exactly this purpose when using gdb directly.

Please use a different channel to get V8 support, this is purely for content on v8.dev:
- https://stackoverflow.com/questions/tagged/v8
- v8-dev@googlegroups.com 
- https://v8.dev/bug
