### ISSUE TITLE
Add option to search the docs

### ISSUE THREAD

**Issue by gsathya** [v8/v8.dev#64]
It's kinda hard to find the info I'm looking for if I don't know the exact page. Previously I used the github search to find stuff on the wiki.

**Comment by gsathya** [comment]
For anyone else who might hit this, my current hack is to use google search with the site keyword like this `site:v8.dev rebaseline`

**Comment by mathiasbynens** [comment]
I have this in `chrome://settings/searchEngines`:

![](https://user-images.githubusercontent.com/81942/48382926-6d6bd100-e698-11e8-8dd1-ee812af4a0f6.png)

Whenever I enter `v8d rebaseline` into my address bar, it takes me to those search results.

**Comment by mathiasbynens** [comment]
We could build a search index at build time and save it as a JSON file, which we could then use to search the site inline… But I’m worried that it would be a lot of effort for something that’s still gonna suck compared to Google Search. 🤔

**Comment by gsathya** [comment]
We could something like this: https://www.netlify.com/blog/2017/10/10/replacing-our-search-with-algolia/ using algolia.

**Comment by xtuc** [comment]
cc @haroenv, I think that Algolia would be a good fit!

**Comment by Haroenv** [comment]
Let me know if you have any questions on doing the search with e.g. DocSearch :)

**Comment by gsathya** [comment]
[Docsearch](https://community.algolia.com/docsearch/) looks amazing.

**Comment by s-pace** [comment]
👋 @gsathya ,

I am working at algolia with @Haroenv, focusing on DocSearch.

We would love to help your project. Its content is so great and helpful for the community. We will extend the search to the blog part.

I have made a quick demo that you [can find here](https://v8_dev-docsearch.surge.sh/) (The position of the bar can be easily changed):

[![Preview of DocSearch + v8_dev](https://cl.ly/ec08cf6c4e3a/download/Screen%20Recording%202018-11-20%20at%2011.49%20AM.gif)](https://v8_dev-docsearch.surge.sh/)

It is quite straight forward to integrate it within your website, you will need to copy and paste the following code:

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '48208fdce8fce1da5356f03c027f067c',
  indexName: 'v8_dev',
  inputSelector: '### REPLACE ME ####',
  algoliaOptions: { 'facetFilters': ["tags:$TAGS"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

- Add a search input in your page. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.

- Replace $TAGS with the tags you want to search on. The list of possible tags is hardcoded in the config. So as of today you have: `blog`, `docs`

  For example if you want to refine the search to the tags "blog" just specify: 
```js
'facetFilters': ["tags:blog"]
```

I can assist you in such endeavour. Feel free to ping.

You can also [fill out the form](https://community.algolia.com/docsearch/apply.html) available on our website. It will help us to grant you access to the full algolia analytics we provide regarding your search usage.

Everything is entirely free.

**Comment by mathiasbynens** [comment]
Thank you for putting that demo together, @s-pace!

----

In general, adding search functionality to v8.dev comes at a cost, no matter which approach we go with. There are pros and cons to each approach:

- approach A: no search functionality (i.e. the current approach)
     - pro: no perf overhead at all
     - con: people wishing to search must use search engines
- approach B: a simple Google Search input
    - pro: minor overhead (it’s just some HTML + CSS)
    - pro: Google Search works pretty well
    - con: viewing search results requires temporarily leaving the website
- approach C: a client-side search
    - pro: search results show up inline — no need to leave the website
    - con: perf overhead: cost of loading + parsing + compiling JS, and loading additional CSS
        - some stats for DocSearch specifically:
            - The latest `docsearch.min.css` is ~5.8 KB, and `docsearch.min.js` is ~45.4 KB. (@Haroenv @s-pace Is there anything that can be done to reduce these bundle sizes?)
            - In contrast, v8.dev currently has 2 KB of CSS and <1 KB of JS.
            - By adopting DocSearch, we’d be increasing our CSS bundle by 3× and our JS bundle by 45×. 😱 

I’m personally not convinced that v8.dev search functionality is important enough to justify paying the performance cost.

If other team members consider search to be important, I _could_ possibly be convinced to go with approach B. Alternatively, we could experiment with approach C but on a separate `/search` page that limits the cost to that one page (as opposed to every single page on v8.dev). What do people think?

**Comment by Haroenv** [comment]
Yes, for an ultra-minimal page like v8, currently docsearch might be on the big size. There’s no real “easy” ways how to get it massively smaller for now, but it’s something we will work on in the future

**Comment by s-pace** [comment]
@mathiasbynens 

Thank you for sharing your concern. Since performance is the main blocker here, you can also load it in an asynchronous way. You will need to use the following snippet.

```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js" onload="docsearch({apiKey: '48208fdce8fce1da5356f03c027f067c',
indexName: 'v8_dev',
inputSelector: '### REPLACE ME ####',
algoliaOptions: { 'facetFilters': ["tags:$TAGS"] },
debug: false // Set debug to true if you want to inspect the dropdown
})" async=""></script>
```

As @Haroenv raised, we are working on streamlining these assets.

**Comment by xtuc** [comment]
@mathiasbynens I think that the search is very valuable. The index doesn't always reflect the content of the page, especially for the release notes.  

Also if the async version isn't enough, as a user, I'm fine clinking on a search button/page and waiting a few seconds to load DocSearch.

**Comment by mathiasbynens** [comment]
Thanks everyone for your feedback on this issue. We don't currently plan on adding search functionality to v8.dev. Closing this issue for now.
