### ISSUE TITLE
[Feature] Consider parsing Typescript and use it for code generation

### ISSUE THREAD

**Issue by dev-ardi** [v8/v8.dev#734]
This might be a very "out there" feature request and I doubt that will be accepted but just wanted to have a discussion.

Typescript is the *de-facto* standard for writing large javascript applications which must be transpiled to JS, often losing context and guarantees.

While many of the types by Typescript can be a lie most of the time they are not and they can be a hint for early codegen, and some invariants can assured.

**Comment by camillobruni** [comment]
While this is an interesting topic, this is not the right venue or issue tracer.
Please use https://v8.dev/bug to file new bugs.
