### ISSUE TITLE
use `standard interpreter` in different languages outside of `nodejs` or `v8`

### ISSUE THREAD

**Issue by ganeshkbhat** [v8/v8.dev#736]
### What is the problem this feature will solve?

use `standard interpreter` in different languages outside of `nodejs` or `v8`

### What is the feature you are proposing to solve the problem?

consider allowing `libnode.h` (`libnode.a`/ `libnode.lib`) and `libnode.wasm` for `nodejs runtime environment`. This makes `nodejs`/ `v8` environment available in other environments.

### What alternatives have you considered?

There is a lot of effort with some good, many half baked wrappers, codes, and efforts

- https://github.com/denoland/rusty_v8
- https://github.com/phpv8/v8js
- https://github.com/JavascriptNet/Javascript.Net
- https://github.com/denoland/rusty_v8
- https://github.com/plv8/plv8
- https://github.com/lazytiger/go-v8
- https://github.com/rubyjs/libv8
- https://github.com/pmed/v8-nuget
- https://github.com/dflemstr/v8-rs
- https://github.com/crossle/V8Android
- https://github.com/caoccao/Javet
- https://github.com/jdryg/v8-binaries
- https://github.com/xaxxon/v8toolkit
- https://github.com/dominiek/ruby-v8
- https://github.com/sol/v8

**Comment by camillobruni** [comment]
This not the right issue tracker, please use https://v8.dev/bug to file new bugs.
