### ISSUE TITLE
I found a standard impementation bug

### ISSUE THREAD

**Issue by AeolusZane** [v8/v8.dev#765]
In a new recursion, a variable declared with "let", should be initialized with a new "let", but in below's demo, it didn't. it seems executed like "var" instead of "let". so when it runs, it would be "Maximum call stack size exceeded...".
```javascript
let cur;
for(let i=5,last=()=>{};i>=0;i--){
    cur = ()=>{
        console.log(i);
        last()
    };
    last = cur;
}
cur()
```

however, by this way, the result executed as expected.
```
let cur;
for(let i=5,last=()=>{};i>=0;last = cur,last = cur,i--){
    cur = ()=>{
        console.log(i);
        last()
    };
}
cur()
```

**Comment by camillobruni** [comment]
Please report this on the [v8 issue tracker](https://v8.dev/bug). This here is just for the v8.dev website.

**Comment by AeolusZane** [comment]
ok, I got it. thx for your reply~
