### ISSUE TITLE
document error

### ISSUE THREAD

**Issue by Zou4495** [v8/v8.dev#780]
line 113

Naturally, we can't share where there is a split. There is a transition from Map2 over to Map4 if the "experience" property is added, and over to Map3 if the "prominence" property is added. You can see **Map4 and Map4** sharing DescriptorArray2 in the same way that DescriptorArray1 was shared among three Maps.

From the diagram, this should be **Map4 and Map5**

**Comment by LeszekSwirski** [comment]
Good catch, thanks, you're right.
