### ISSUE TITLE
Dead links in Blink layout tests

### ISSUE THREAD

**Issue by xtuc** [v8/v8.dev#91]
https://chromium.googlesource.com/chromium/src/+/master/docs/testing/layout_tests.md and https://chromium.googlesource.com/chromium/src/+/master/docs/testing/layout_test_expectations.md#How-to-rebaseline are dead.

**Comment by mathiasbynens** [comment]
Looks like these files were renamed in <https://chromium.googlesource.com/chromium/src/+/59ffb020bd6fc65b67dd11cafa0198eb80e225bc>. @xtuc, would you like to submit a PR?

**Comment by xtuc** [comment]
Yes sure, thanks for the information.
